/* ============================================================================
 * ORIGINAL PRODUCT SEED DATA
 * ----------------------------------------------------------------------------
 * This was the site's product catalogue before it moved into the database.
 * It only feeds `prisma/seed.js` now (used to (re)populate a fresh database,
 * e.g. after a reset). To edit the live catalogue, use /admin/products —
 * changes there do not touch this file.
 *
 * ⚠️  The `specs` values below (moisture, packing, shelf life) were TYPICAL
 * INDUSTRY VALUES used as sensible defaults, not verified figures. Confirm
 * real specifications with your production team before relying on them.
 * ==========================================================================*/

const products = [
  // ---------------------------------------------------------------- VEGETABLES
  {
    slug: "white-onion",
    category: "dehydrated-vegetables",
    name: "Dehydrated White Onion",
    image: null,
    form: "flakes",
    colors: { base: "#f1f5f9", accent: "#cbd5e1", deep: "#94a3b8" },
    short: "Pungent white onion in kibbled, chopped, minced and granule cuts.",
    description:
      "Air-dried white onion with a clean, pungent aroma and pale ivory colour. A staple ingredient for seasoning blends, soups, sauces, snack coatings and ready meals, rehydrating quickly to near-fresh texture.",
    forms: ["Kibbled", "Chopped", "Minced", "Granules", "Powder"],
    applications: ["Seasoning blends", "Soups & sauces", "Snack coatings", "Ready meals"],
    specs: { Moisture: "Max 5%", Cut: "As per buyer specification", Packing: "20 kg / 25 kg", "Shelf Life": "24 months" },
  },
  {
    slug: "red-onion",
    category: "dehydrated-vegetables",
    name: "Dehydrated Red Onion",
    image: null,
    form: "flakes",
    colors: { base: "#f5d0fe", accent: "#d946ef", deep: "#a21caf" },
    short: "Rich colour and sharper flavour for visible-inclusion applications.",
    description:
      "Dehydrated red onion retains its characteristic purple-pink hue, making it the preferred choice where the onion should be visible in the finished product — salad toppings, garnishes, premium seasoning mixes and retail packs.",
    forms: ["Kibbled", "Chopped", "Minced", "Granules", "Powder"],
    applications: ["Garnishes & toppings", "Premium seasonings", "Retail packs", "Salad mixes"],
    specs: { Moisture: "Max 5%", Cut: "As per buyer specification", Packing: "20 kg / 25 kg", "Shelf Life": "24 months" },
  },
  {
    slug: "garlic",
    category: "dehydrated-vegetables",
    name: "Dehydrated Garlic",
    image: null,
    form: "slices",
    colors: { base: "#fefce8", accent: "#fde68a", deep: "#d4a017" },
    short: "Cloves, flakes, granules and powder with strong aroma retention.",
    description:
      "Carefully dried garlic that holds its sharp aroma and off-white colour. Supplied from whole cloves through to fine powder, it is one of our highest-volume lines for spice houses and food manufacturers.",
    forms: ["Cloves", "Flakes", "Chopped", "Granules", "Powder"],
    applications: ["Spice blends", "Marinades", "Sauces & pastes", "Instant foods"],
    specs: { Moisture: "Max 6%", Cut: "As per buyer specification", Packing: "20 kg / 25 kg", "Shelf Life": "24 months" },
  },
  {
    slug: "tomato",
    category: "dehydrated-vegetables",
    name: "Dehydrated Tomato",
    image: null,
    form: "dices",
    colors: { base: "#fecaca", accent: "#ef4444", deep: "#b91c1c" },
    short: "Deep-red dices, flakes and powder with natural tang.",
    description:
      "Ripe tomatoes dried to concentrate their natural sweetness and acidity. The strong red colour survives cooking well, making it valuable for soups, pasta sauces, pizza toppings and seasoning bases.",
    forms: ["Dices", "Flakes", "Slices", "Powder"],
    applications: ["Soups & sauces", "Pizza toppings", "Seasoning bases", "Ready meals"],
    specs: { Moisture: "Max 7%", Cut: "5–10 mm dices (typical)", Packing: "10 kg / 20 kg", "Shelf Life": "18 months" },
  },
  {
    slug: "carrot",
    category: "dehydrated-vegetables",
    name: "Dehydrated Carrot",
    image: null,
    form: "dices",
    colors: { base: "#fed7aa", accent: "#f97316", deep: "#c2410c" },
    short: "Bright orange dices and flakes for soups and ready meals.",
    description:
      "Dehydrated carrot holds a vivid orange colour and natural sweetness. Widely used in instant soups, noodle seasoning sachets, ready meals and institutional catering where quick rehydration matters.",
    forms: ["Dices", "Flakes", "Slices", "Granules", "Powder"],
    applications: ["Instant soups", "Noodle sachets", "Ready meals", "Baby food"],
    specs: { Moisture: "Max 6%", Cut: "5–10 mm dices (typical)", Packing: "10 kg / 20 kg", "Shelf Life": "18 months" },
  },
  {
    slug: "beetroot",
    category: "dehydrated-vegetables",
    name: "Dehydrated Beetroot",
    image: null,
    form: "slices",
    colors: { base: "#fbcfe8", accent: "#db2777", deep: "#9d174d" },
    short: "Intense natural crimson for colouring and nutrition applications.",
    description:
      "Beetroot dried to preserve its deep crimson pigment. Sought after as a natural colourant and for nutraceutical applications, alongside conventional culinary use in soups, breads and blends.",
    forms: ["Slices", "Dices", "Flakes", "Powder"],
    applications: ["Natural colouring", "Nutraceuticals", "Bakery", "Health beverages"],
    specs: { Moisture: "Max 6%", Cut: "As per buyer specification", Packing: "10 kg / 20 kg", "Shelf Life": "18 months" },
  },
  {
    slug: "green-peas",
    category: "dehydrated-vegetables",
    name: "Dehydrated Green Peas",
    image: null,
    form: "granules",
    colors: { base: "#bbf7d0", accent: "#22c55e", deep: "#15803d" },
    short: "Whole dried peas that rehydrate to a tender, bright green.",
    description:
      "Green peas dried whole, retaining colour and shape. A visible-inclusion favourite in instant meal cups, soup mixes, pilaf blends and snack applications.",
    forms: ["Whole", "Split", "Powder"],
    applications: ["Instant meals", "Soup mixes", "Pilaf & rice blends", "Snacks"],
    specs: { Moisture: "Max 7%", Cut: "Whole", Packing: "20 kg / 25 kg", "Shelf Life": "18 months" },
  },
  {
    slug: "spinach",
    category: "dehydrated-vegetables",
    name: "Dehydrated Spinach",
    image: null,
    form: "flakes",
    colors: { base: "#bbf7d0", accent: "#16a34a", deep: "#14532d" },
    short: "Deep green leaf flakes and powder, high in natural pigment.",
    description:
      "Spinach leaves dried gently to hold their deep green colour and nutrient profile. Used in pasta doughs, green blends, soups, health drinks and nutraceutical formulations.",
    forms: ["Leaf flakes", "Chopped", "Powder"],
    applications: ["Pasta & noodles", "Health beverages", "Soups", "Nutraceuticals"],
    specs: { Moisture: "Max 6%", Cut: "As per buyer specification", Packing: "10 kg / 15 kg", "Shelf Life": "18 months" },
  },
  {
    slug: "ginger",
    category: "dehydrated-vegetables",
    name: "Dehydrated Ginger",
    image: null,
    form: "slices",
    colors: { base: "#fef3c7", accent: "#f59e0b", deep: "#b45309" },
    short: "Pungent ginger in slices, granules and fine powder.",
    description:
      "Dried ginger with a warm, pungent bite. Supplied as slices for infusion and beverage use, or milled to powder for spice blends, bakery and instant drink applications.",
    forms: ["Slices", "Chopped", "Granules", "Powder"],
    applications: ["Spice blends", "Instant beverages", "Bakery", "Ayurvedic formulations"],
    specs: { Moisture: "Max 8%", Cut: "As per buyer specification", Packing: "20 kg / 25 kg", "Shelf Life": "24 months" },
  },

  // -------------------------------------------------------------------- FRUITS
  {
    slug: "banana",
    category: "dehydrated-fruits",
    name: "Dehydrated Banana",
    image: null,
    form: "slices",
    colors: { base: "#fef9c3", accent: "#facc15", deep: "#a16207" },
    short: "Sweet banana slices, dices and flakes for cereals and snacks.",
    description:
      "Ripe bananas dried into slices and flakes with concentrated natural sweetness. A core ingredient for breakfast cereals, trail mixes, bakery inclusions and infant nutrition.",
    forms: ["Slices", "Dices", "Flakes", "Powder"],
    applications: ["Breakfast cereals", "Trail mixes", "Bakery", "Infant nutrition"],
    specs: { Moisture: "Max 5%", Cut: "As per buyer specification", Packing: "10 kg / 15 kg", "Shelf Life": "18 months" },
  },
  {
    slug: "mango",
    category: "dehydrated-fruits",
    name: "Dehydrated Mango",
    image: null,
    form: "slices",
    colors: { base: "#fde68a", accent: "#f59e0b", deep: "#c2410c" },
    short: "Golden mango slices and dices with strong tropical aroma.",
    description:
      "Dried from ripe Indian mango varieties, holding a rich golden colour and pronounced tropical aroma. Used in snacking, bakery inclusions, cereals, confectionery and premium retail packs.",
    forms: ["Slices", "Dices", "Strips", "Powder"],
    applications: ["Snacking", "Bakery inclusions", "Confectionery", "Retail packs"],
    specs: { Moisture: "Max 5%", Cut: "As per buyer specification", Packing: "10 kg / 15 kg", "Shelf Life": "18 months" },
  },
  {
    slug: "pineapple",
    category: "dehydrated-fruits",
    name: "Dehydrated Pineapple",
    image: null,
    form: "dices",
    colors: { base: "#fef08a", accent: "#eab308", deep: "#854d0e" },
    short: "Tangy-sweet rings, dices and tidbits.",
    description:
      "Pineapple dried to a chewy texture with its characteristic sweet-tart balance intact. Popular in muesli, trail mixes, baked goods and dried fruit assortments.",
    forms: ["Rings", "Dices", "Tidbits", "Powder"],
    applications: ["Muesli & granola", "Trail mixes", "Bakery", "Fruit assortments"],
    specs: { Moisture: "Max 6%", Cut: "As per buyer specification", Packing: "10 kg / 15 kg", "Shelf Life": "18 months" },
  },
  {
    slug: "papaya",
    category: "dehydrated-fruits",
    name: "Dehydrated Papaya",
    image: null,
    form: "dices",
    colors: { base: "#fed7aa", accent: "#fb923c", deep: "#c2410c" },
    short: "Soft orange dices with a mild, sweet profile.",
    description:
      "Papaya dried into tender dices and strips with a gentle sweetness and bright orange tone. Frequently used in dried fruit mixes, cereals, bakery and confectionery.",
    forms: ["Dices", "Strips", "Slices", "Powder"],
    applications: ["Dried fruit mixes", "Cereals", "Bakery", "Confectionery"],
    specs: { Moisture: "Max 6%", Cut: "As per buyer specification", Packing: "10 kg / 15 kg", "Shelf Life": "18 months" },
  },
  {
    slug: "apple",
    category: "dehydrated-fruits",
    name: "Dehydrated Apple",
    image: null,
    form: "slices",
    colors: { base: "#fee2e2", accent: "#f87171", deep: "#b91c1c" },
    short: "Rings, dices and flakes with clean, mild sweetness.",
    description:
      "Apple dried into rings, dices and flakes with a mild, versatile sweetness. Widely used in bakery fillings, cereals, infant food, tea blends and healthy snacking.",
    forms: ["Rings", "Dices", "Flakes", "Powder"],
    applications: ["Bakery fillings", "Cereals", "Tea blends", "Infant food"],
    specs: { Moisture: "Max 6%", Cut: "As per buyer specification", Packing: "10 kg / 15 kg", "Shelf Life": "18 months" },
  },
  {
    slug: "lemon",
    category: "dehydrated-fruits",
    name: "Dehydrated Lemon",
    image: null,
    form: "slices",
    colors: { base: "#fef9c3", accent: "#eab308", deep: "#a16207" },
    short: "Bright citrus slices and peel for beverages and seasoning.",
    description:
      "Lemon dried as slices and peel, holding a sharp citrus aroma. Used in herbal tea blends, beverage garnishes, seasoning mixes and confectionery.",
    forms: ["Slices", "Peel", "Granules", "Powder"],
    applications: ["Herbal teas", "Beverages", "Seasoning mixes", "Confectionery"],
    specs: { Moisture: "Max 7%", Cut: "As per buyer specification", Packing: "5 kg / 10 kg", "Shelf Life": "18 months" },
  },

  // ------------------------------------------------------------------- POWDERS
  {
    slug: "mango-powder",
    category: "fruit-vegetable-powders",
    name: "Mango Powder",
    image: null,
    form: "powder",
    colors: { base: "#fde68a", accent: "#f59e0b", deep: "#b45309" },
    short: "Spray-dried mango powder for beverages, bakery and dairy.",
    description:
      "Free-flowing mango powder with strong flavour carry-through and a warm golden colour. Formulated for instant beverages, dairy applications, bakery, confectionery and nutritional blends.",
    forms: ["Spray-dried", "Freeze-dried", "Air-dried"],
    applications: ["Instant beverages", "Dairy & ice cream", "Bakery", "Nutritional blends"],
    specs: { Moisture: "Max 5%", Mesh: "80–100 mesh (typical)", Packing: "10 kg / 20 kg", "Shelf Life": "18 months" },
  },
  {
    slug: "onion-powder",
    category: "fruit-vegetable-powders",
    name: "Onion Powder",
    image: null,
    form: "powder",
    colors: { base: "#f8fafc", accent: "#cbd5e1", deep: "#64748b" },
    short: "Fine, free-flowing onion powder for seasoning systems.",
    description:
      "Uniformly milled onion powder with consistent pungency, engineered to disperse evenly through dry seasoning systems, snack coatings, sauces and soup bases.",
    forms: ["Powder", "Granules", "Toasted"],
    applications: ["Dry seasonings", "Snack coatings", "Soup bases", "Sauces"],
    specs: { Moisture: "Max 6%", Mesh: "80–100 mesh (typical)", Packing: "20 kg / 25 kg", "Shelf Life": "24 months" },
  },
  {
    slug: "garlic-powder",
    category: "fruit-vegetable-powders",
    name: "Garlic Powder",
    image: null,
    form: "powder",
    colors: { base: "#fefce8", accent: "#fde68a", deep: "#a16207" },
    short: "Strong-aroma garlic powder milled to a consistent mesh.",
    description:
      "Garlic milled to a uniform, free-flowing powder with high aroma retention. A workhorse ingredient across spice blends, marinades, ready meals and snack seasoning.",
    forms: ["Powder", "Granules", "Roasted"],
    applications: ["Spice blends", "Marinades", "Ready meals", "Snack seasoning"],
    specs: { Moisture: "Max 6%", Mesh: "80–100 mesh (typical)", Packing: "20 kg / 25 kg", "Shelf Life": "24 months" },
  },
  {
    slug: "beetroot-powder",
    category: "fruit-vegetable-powders",
    name: "Beetroot Powder",
    image: null,
    form: "powder",
    colors: { base: "#fbcfe8", accent: "#db2777", deep: "#831843" },
    short: "Vivid natural red powder for colouring and wellness products.",
    description:
      "Beetroot powder delivering an intense natural crimson without synthetic colourants. Used across health beverages, supplements, bakery, pasta and clean-label colouring.",
    forms: ["Spray-dried", "Air-dried", "Fine powder"],
    applications: ["Natural colouring", "Health beverages", "Supplements", "Bakery"],
    specs: { Moisture: "Max 5%", Mesh: "80–100 mesh (typical)", Packing: "10 kg / 20 kg", "Shelf Life": "18 months" },
  },
  {
    slug: "spinach-powder",
    category: "fruit-vegetable-powders",
    name: "Spinach Powder",
    image: null,
    form: "powder",
    colors: { base: "#bbf7d0", accent: "#16a34a", deep: "#14532d" },
    short: "Deep green leaf powder for greens blends and nutrition.",
    description:
      "Finely milled spinach powder with a strong green tone, formulated for greens supplements, smoothie blends, pasta, soups and clean-label nutrition products.",
    forms: ["Fine powder", "Coarse powder"],
    applications: ["Greens supplements", "Smoothie blends", "Pasta & noodles", "Soups"],
    specs: { Moisture: "Max 5%", Mesh: "80–100 mesh (typical)", Packing: "10 kg / 15 kg", "Shelf Life": "18 months" },
  },
  {
    slug: "tomato-powder",
    category: "fruit-vegetable-powders",
    name: "Tomato Powder",
    image: null,
    form: "powder",
    colors: { base: "#fecaca", accent: "#ef4444", deep: "#991b1b" },
    short: "Concentrated tomato powder for soups, sauces and seasoning.",
    description:
      "Tomato dried and milled into a concentrated powder carrying natural colour, acidity and umami. Reconstitutes readily for soups, sauces, seasoning bases and snack coatings.",
    forms: ["Spray-dried", "Drum-dried", "Fine powder"],
    applications: ["Soups & sauces", "Seasoning bases", "Snack coatings", "Ready meals"],
    specs: { Moisture: "Max 5%", Mesh: "80–100 mesh (typical)", Packing: "10 kg / 20 kg", "Shelf Life": "18 months" },
  },

  // ------------------------------------------------------------- INSTANT FOODS
  {
    slug: "instant-soup",
    category: "instant-food",
    name: "Instant Soup Mixes",
    image: null,
    form: "blend",
    colors: { base: "#fed7aa", accent: "#f97316", deep: "#9a3412" },
    short: "Just-add-hot-water soup bases in multiple variants.",
    description:
      "Shelf-stable soup mixes built on our own dehydrated vegetables and powders. Available in tomato, sweet corn, mixed vegetable, hot & sour and other variants, in bulk or retail sachets.",
    forms: ["Retail sachets", "Bulk packs", "Private label"],
    applications: ["Retail", "HoReCa", "Institutional catering", "Travel & camping"],
    specs: { Preparation: "Add hot water, 3–5 min", Packing: "Sachets / bulk", "Shelf Life": "12–18 months", "Min. Order": "Discuss with us" },
  },
  {
    slug: "khichdi-mix",
    category: "instant-food",
    name: "Instant Khichdi Mix",
    image: null,
    form: "blend",
    colors: { base: "#fef3c7", accent: "#eab308", deep: "#854d0e" },
    short: "Traditional rice-and-lentil meal, ready in minutes.",
    description:
      "A complete rice-and-lentil meal with dehydrated vegetables and spices, requiring only hot water. Popular with the ethnic-foods trade, travel retail and outdoor and emergency-ration buyers.",
    forms: ["Retail packs", "Bulk packs", "Private label"],
    applications: ["Ethnic foods retail", "Travel retail", "Camping & outdoor", "Emergency rations"],
    specs: { Preparation: "Add hot water, 5–8 min", Packing: "Retail / bulk", "Shelf Life": "12 months", "Min. Order": "Discuss with us" },
  },
  {
    slug: "upma-poha-mix",
    category: "instant-food",
    name: "Instant Upma & Poha Mix",
    image: null,
    form: "blend",
    colors: { base: "#fef9c3", accent: "#facc15", deep: "#a16207" },
    short: "Classic Indian breakfast mixes with dehydrated vegetables.",
    description:
      "Ready-to-cook upma and poha bases blended with our dehydrated vegetables and tempered spices. Formulated for consistent texture after rehydration and a long ambient shelf life.",
    forms: ["Retail packs", "Bulk packs", "Private label"],
    applications: ["Breakfast retail", "Ethnic foods export", "HoReCa", "Institutional"],
    specs: { Preparation: "Add hot water, 5 min", Packing: "Retail / bulk", "Shelf Life": "12 months", "Min. Order": "Discuss with us" },
  },
  {
    slug: "vegetable-blend",
    category: "custom-blends",
    name: "Custom Vegetable Blends",
    image: null,
    form: "blend",
    colors: { base: "#d9f99d", accent: "#65a30d", deep: "#3f6212" },
    short: "Your recipe, our processing line — built to specification.",
    description:
      "Bespoke dehydrated vegetable and fruit blends produced to your ratio, cut size and mesh specification. We handle sample development, iteration and scale-up to production volumes under your brand.",
    forms: ["Custom ratio", "Custom cut", "Private label", "Bulk or retail"],
    applications: ["Own-brand programmes", "Contract manufacturing", "Product development", "OEM supply"],
    specs: { Development: "Samples on request", Packing: "As per requirement", "Shelf Life": "Blend dependent", "Min. Order": "Discuss with us" },
  },
];

module.exports = products;
